services:
  - type: web
    name: backend
    env: node
    buildCommand: |
      cd backend
      npm install
      pip3 install -r /src/scripts/requirements.txt
    startCommand: node backend/server.js
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
